defaults:
  - qwen3_4b_instruct_terminal_teacher_answer_rl_from_sft99_h200
  - _self_

experiment_name: qwen3-4b-instruct-terminal-teacher-answer-rl-from-sft99-medium-b128-s2-500step-safe32768-o768-s50-h200

gconfig:
  max_new_tokens: 768
  max_tokens: 32768

eval_gconfig:
  max_new_tokens: 768
  max_tokens: 32768

actor:
  max_new_tokens: ${gconfig.max_new_tokens}
  mb_spec:
    max_tokens_per_mb: 32768

sglang:
  context_length: 32768
  max_prefill_tokens: 32768

vllm:
  max_model_len: 32768

train_dataset:
  max_length: 32768

saver:
  freq_steps: 50

